export const registry = [
  {
    type: "Button",
    label: "Button",
    defaultProps: {
      text: "Click Me",
      className: "bg-blue-500 text-white px-4 py-2 rounded-lg font-medium hover:bg-blue-600 transition",
      backgroundColor: "#3b82f6",
      color: "#ffffff",
      padding: "8px 16px",
      borderRadius: "8px",
    },
    propsSchema: {
      text: { type: "text", label: "Button Text" },
      className: { type: "text", label: "Tailwind Classes" },
      backgroundColor: { type: "color", label: "Background Color" },
      color: { type: "color", label: "Text Color" },
      padding: { type: "text", label: "Padding (CSS)" },
      borderRadius: { type: "text", label: "Border Radius (CSS)" },
    },
  },
  {
    type: "Container",
    label: "Container",
    defaultProps: {
      className: "p-4 border border-slate-300 rounded-lg bg-slate-50 min-h-[200px]",
      backgroundColor: "#f8fafc",
      padding: "16px",
      border: "1px solid #cbd5e1",
      borderRadius: "8px",
      minHeight: "200px",
    },
    propsSchema: {
      className: { type: "text", label: "Tailwind Classes" },
      backgroundColor: { type: "color", label: "Background Color" },
      padding: { type: "text", label: "Padding (CSS)" },
      border: { type: "text", label: "Border (CSS)" },
      borderRadius: { type: "text", label: "Border Radius (CSS)" },
      minHeight: { type: "text", label: "Min Height (CSS)" },
    },
  },
  {
    type: "Sidebar",
    label: "Sidebar",
    defaultProps: {
      className: "bg-red-700 rounded-4xl p-4 min-h-[300px]",
      backgroundColor: "#b91c1c",
      borderRadius: "32px",
      padding: "16px",
      minHeight: "300px",
    },
    propsSchema: {
      className: { type: "text", label: "Tailwind Classes" },
      backgroundColor: { type: "color", label: "Background Color" },
      borderRadius: { type: "text", label: "Border Radius (CSS)" },
      padding: { type: "text", label: "Padding (CSS)" },
      minHeight: { type: "text", label: "Min Height (CSS)" },
    },
  },
];